#!/bin/bash
set -euo pipefail
IFS=$'\n\t'

cd "$(dirname "$0")/.."

# script/bootstrap: Resolve all dependencies that the application requires to
#                   run.

CI_BUILD=${CI_BUILD-false}

echo -e '\n== Bootstrapping dependencies =='

[[ $(ruby -v) == 'ruby 2.5'* ]] || {
  echo -e '\nPlease install Ruby 2.5 and then run this script again.'
  exit 1
}

which redis-server 2>&1 >/dev/null || {
  if [[ $CI_BUILD != true ]]; then
    echo -e '\nPlease install Redis (redis-server) and then run this script again.'
    echo -e 'If your running OSX the you can install it by running:'
    echo -e '  $ brew install redis'
    echo -e 'or if you use apt-get:'
    echo -e '  $ sudo apt-get -y install redis-server'
  fi
}

which bundle 2>&1 >/dev/null || {
  echo -e '\n== Installing bundler =='
  gem install bundler --conservative
}

which rubocop 2>&1 >/dev/null || {
  if [[ $CI_BUILD != true ]]; then
    echo -e '\n== Installing rubocop =='
    gem install rubocop
  fi
}

which foreman 2>&1 >/dev/null || {
  if [[ $CI_BUILD != true ]]; then
    echo -e '\n== Installing foreman =='
    gem install foreman
  fi
}

echo -e '\n== Installing gem dependencies =='
bundle check || bundle install --without production
echo -e '\n== Bootstrap done =='
