#!/bin/bash
set -euo pipefail
IFS=$'\n\t'

cd "$(dirname "$0")/.."

# script/cibuild: Run the test suite from CI.

CIRCLE_CI=${CIRCLE_CI:-false}

# Allow called scripts to detect that its being run by CI
export CI_BUILD=true

echo -e '\n== Running cibuild =='
export RAILS_ENV=test
export RAKE_ENV=test
export RUN_NESTED_GEMS_SPECS=true
export RAILS_EAGER_LOAD_IN_TEST=true
export DISABLE_SPRING=1

script/bootstrap

bin/rails db:create db:schema:load

export LINT_FACTORY=true
export RUBOCOP=false
export CHECK_DB_INDEXES=false
export CHECK_DB_UNIQ_INDEXES=false
if [[ $CIRCLE_CI == 'true' ]]; then
  script/test -r rspec_junit_formatter --format RspecJunitFormatter -o $CIRCLE_TEST_REPORTS/rspec/junit.xml spec
else
  script/test spec
fi
