#!/bin/bash
set -euo pipefail
IFS=$'\n\t'

cd "$(dirname "$0")/.."

# script/console: Launch a console for the application.

echo -e '\n== Initializing console =='
bin/rails console
echo -e '\n== Console done =='
