#!/bin/bash
set -euo pipefail
IFS=$'\n\t'

cd "$(dirname "$0")/.."

# script/deploy: Deploy the application.

echo -e '\n== Deploying application =='
git push heroku master
heroku run rails db:migrate
echo -e '\n== Deploy done =='
