#!/bin/bash
set -euo pipefail
IFS=$'\n\t'

cd "$(dirname "$0")/.."

# script/doc: Generate application documentation.

echo -e '\n== Generating documentation =='
# ensure everything in the app is up to date.
script/update

bin/rake apipie:static
echo -e '\n== Doc done =='
