#!/bin/bash
set -euo pipefail
IFS=$'\n\t'

cd "$(dirname "$0")/.."

# script/doc: Generate application documentation.

echo -e '\n== Generating documentation =='
# ensure everything in the app is up to date.
script/update

echo -e '\n== Generating API response examples =='
bin/rake docs:response_examples

echo -e '\n== Generating API documentation =='
bin/rake apipie:static
echo -e '\n== Docs generated =='
