#!/bin/bash
set -euo pipefail
IFS=$'\n\t'

cd "$(dirname "$0")/.."

# script/server: Launch the application and any extra required processes
#                locally.

# ensure everything in the app is up to date.
script/update

RACK_ENV=${RACK_ENV:-development}

server_port=${1:-3000}

echo -e "\n== Starting server on port $port =="
# boot the app and any other necessary processes.
foreman start -p $server_port -f Procfile.dev
echo -e '\n== Server done =='
