#!/bin/bash
set -euo pipefail
IFS=$'\n\t'

cd "$(dirname "$0")/.."

# script/setup: Set up application for the first time after cloning, or set it
#               back to the initial first unused state.

script/bootstrap

echo -e '\n== Preparing database =='
bin/rails db:setup

echo -e '\n== Removing old logs and tempfiles =='
rm -f log/*
rm -rf tmp/cache

if [[ ! -f .env ]]; then
  echo -e '\n== Setting up .env file =='
  cp .sample.env .env
  echo -e '[NOTICE] Make sure you configure your .env file to your liking.'
fi

echo -e '\n== Setup done =='
