#!/bin/bash
set -euo pipefail
IFS=$'\n\t'

cd "$(dirname "$0")/.."

echo -e '\n== Running tests =='
export RAILS_ENV=test
export RAKE_ENV=test
bin/rspec "$@"
test_suite_exit_status=$?

# If token is set send coverage report to CodeClimate
CODECLIMATE_REPO_TOKEN=${CODECLIMATE_REPO_TOKEN-}
if [[ -n $CODECLIMATE_REPO_TOKEN ]]; then
  bundle exec codeclimate-test-reporter
else
  echo '[warn] Not sending test coverage report data (CODECLIMATE_REPO_TOKEN not set).'
fi

exit $test_suite_exit_status
