#!/bin/bash
set -euo pipefail
IFS=$'\n\t'

cd "$(dirname "$0")/.."
RUN_NESTED_GEMS_SPECS=${RUN_NESTED_GEMS_SPECS-:'false'}

run_frilans_finans_api_specs=''
run_json_api_helpers_specs=''
if [[ $RUN_NESTED_GEMS_SPECS == 'true' ]]; then
  run_json_api_helpers_specs='lib/json_api_helpers/spec'
  run_frilans_finans_api_specs='lib/frilans_finans_api/spec'
fi

echo -e '\n== Running tests =='
export RAILS_ENV=test
export RAKE_ENV=test
bin/rspec "$@" $run_json_api_helpers_specs $run_frilans_finans_api_specs
