#!/bin/bash
set -euo pipefail
IFS=$'\n\t'

cd "$(dirname "$0")/.."

echo -e '\n== Updating to run application for its current checkout =='

script/bootstrap

echo -e '\n== Migrating database =='
bin/rake db:migrate

echo -e '\n== Removing old logs and tempfiles =='
bin/rails log:clear tmp:clear

echo -e '\n== Restarting application server =='
bin/rails restart

echo -e '\n== Update done =='
